# Generated by Django 6.0.3 on 2026-03-22 17:09

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=150)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nome", models.CharField(max_length=255)),
                ("CPF", models.CharField(blank=True, max_length=20, null=True)),
                ("Nascimento", models.DateField(blank=True, null=True)),
                (
                    "Profissao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JOB_ENTREPRENEUR", "Empresário"),
                            ("JOB_EXECUTIVE", "Executivo"),
                            ("JOB_PROFESSIONAL", "Profissional liberal"),
                            ("JOB_CLT", "Funcionário CLT"),
                            ("JOB_INVESTOR", "Investidor"),
                            ("JOB_RETIRED", "Aposentado"),
                            ("JOB_OTHER", "Outro"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "Profissao_Outro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Estado_Civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MS_SINGLE", "Solteiro"),
                            ("MS_MARRIED", "Casado"),
                            ("MS_DIVORCED", "Divorciado"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Filhos",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CH_NONE", "Sem filhos"),
                            ("CH_DEP", "Dependentes"),
                            ("CH_NODEP", "Independentes"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("Dependentes", models.IntegerField(blank=True, null=True)),
                (
                    "Patrimonio_Financeiro",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "Patrimonio_Imobiliario",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("Qtd_Imoveis", models.IntegerField(blank=True, null=True)),
                (
                    "Renda_Mensal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "Fonte_Renda",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SRC_PROFIT", "Distribuição de lucro"),
                            ("SRC_SALARY", "Salário"),
                            ("SRC_RENT", "Aluguéis"),
                            ("SRC_INVEST", "Investimentos"),
                            ("SRC_RETIREMENT", "Aposentadoria"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Custo_Vida",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "Frequencia_Invest",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Sim"), ("NO", "Não")],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "Valor_Investimento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "Periodo_Invest",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PER_MONTH", "Mensal"),
                            ("PER_QUARTER", "Trimestral"),
                            ("PER_SEM", "Semestral"),
                            ("PER_YEAR", "Anual"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Dividas",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Sim"), ("NO", "Não")],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("Tipo_Divida", models.JSONField(blank=True, null=True)),
                (
                    "Valor_Dividas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("Objetivos", models.JSONField(blank=True, null=True)),
                (
                    "Horizonte",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HZ_SHORT", "Curto prazo"),
                            ("HZ_MEDIUM", "Médio prazo"),
                            ("HZ_LONG", "Longo prazo"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Risco",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RISK_REDUCE", "Reduziria"),
                            ("RISK_HOLD", "Manteria"),
                            ("RISK_BUY", "Compraria mais"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Preferencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PREF_STABLE", "Rendimento estável"),
                            ("PREF_GROWTH", "Crescimento"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Seguro",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Sim"), ("NO", "Não")],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "Seguro_Invalidez",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Sim"), ("NO", "Não")],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "Sucessao",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Sim"), ("NO", "Não")],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "Estrutura_Societaria",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Sim"), ("NO", "Não")],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "Investimento_Exterior",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Sim"), ("NO", "Não")],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "Contato",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONTACT_CLOSE", "Próximo"),
                            ("CONTACT_PERIODIC", "Periódico"),
                            ("CONTACT_STRATEGIC", "Estratégico"),
                            ("CONTACT_ONDEMAND", "Sob demanda"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("Expectativa", models.TextField(blank=True, null=True)),
                ("Nao_Resolvido", models.TextField(blank=True, null=True)),
                ("Criado_Em", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
