# Generated by Django 6.0.3 on 2026-03-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="Nome",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
