# Generated by Django 6.0.3 on 2026-03-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_alter_formsubmission_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="Nome",
            field=models.CharField(default="Sem nome", max_length=255),
            preserve_default=False,
        ),
    ]
